from itertools import permutations, combinations_with_replacement

# list the numbers to use here
numbahs = [2,4,6,8]
# enter the number to calculate here
ansah = 24

numberlist = input("Enter a list of four integers, separated by commas [default: 2,4,6,8]: ")
if numberlist:
    numbahs = [int(n) for n in numberlist.split(',')]
answer = input("Enter a number compute to [default: 24]: ")
if answer:
    ansah = int(answer)

expressions = [
    lambda a,b,c,d: ((a*b)*c)*d,
    lambda a,b,c,d: ((a*b)+c)*d,
    lambda a,b,c,d: ((a+b)*c)*d,
    lambda a,b,c,d: ((a*b)-c)*d,
    lambda a,b,c,d: ((a/b)+c)*d,
    lambda a,b,c,d: ((a-b)*c)*d,
    lambda a,b,c,d: ((a/b)-c)*d,
    lambda a,b,c,d: ((a+b)+c)*d,
    lambda a,b,c,d: ((a+b)-c)*d,
    lambda a,b,c,d: ((a-b)-c)*d,
    lambda a,b,c,d: ((a*b)*c)/d,
    lambda a,b,c,d: ((a*b)/c)/d,
    lambda a,b,c,d: ((a*b)+c)/d,
    lambda a,b,c,d: ((a+b)*c)/d,
    lambda a,b,c,d: ((a*b)-c)/d,
    lambda a,b,c,d: ((a-b)*c)/d,
    lambda a,b,c,d: ((a/b)/c)/d,
    lambda a,b,c,d: ((a/b)+c)/d,
    lambda a,b,c,d: ((a+b)/c)/d,
    lambda a,b,c,d: ((a/b)-c)/d,
    lambda a,b,c,d: ((a-b)/c)/d,
    lambda a,b,c,d: ((a+b)+c)/d,
    lambda a,b,c,d: ((a+b)-c)/d,
    lambda a,b,c,d: ((a-b)-c)/d,
    lambda a,b,c,d: ((a*b)*c)+d,
    lambda a,b,c,d: ((a*b)/c)+d,
    lambda a,b,c,d: ((a*b)+c)+d,
    lambda a,b,c,d: ((a+b)*c)+d,
    lambda a,b,c,d: ((a-b)*c)+d,
    lambda a,b,c,d: ((a/b)/c)+d,
    lambda a,b,c,d: ((a/b)+c)+d,
    lambda a,b,c,d: ((a+b)/c)+d,
    lambda a,b,c,d: ((a-b)/c)+d,
    lambda a,b,c,d: ((a+b)+c)+d,
    lambda a,b,c,d: ((a*b)*c)-d,
    lambda a,b,c,d: ((a*b)/c)-d,
    lambda a,b,c,d: ((a*b)+c)-d,
    lambda a,b,c,d: ((a+b)*c)-d,
    lambda a,b,c,d: ((a*b)-c)-d,
    lambda a,b,c,d: ((a-b)*c)-d,
    lambda a,b,c,d: ((a/b)/c)-d,
    lambda a,b,c,d: ((a/b)+c)-d,
    lambda a,b,c,d: ((a+b)/c)-d,
    lambda a,b,c,d: ((a/b)-c)-d,
    lambda a,b,c,d: ((a-b)/c)-d,
    lambda a,b,c,d: ((a+b)+c)-d,
    lambda a,b,c,d: ((a+b)-c)-d,
    lambda a,b,c,d: ((a-b)-c)-d,
    lambda a,b,c,d: ((a*b)/(c*d),
    lambda a,b,c,d: ((a*b)*(c/d),
    lambda a,b,c,d: ((a*b)+(c*d),
    lambda a,b,c,d: ((a*b)-(c*d),
    lambda a,b,c,d: ((a*b)/(c/d),
    lambda a,b,c,d: ((a/b)/(c*d),
    lambda a,b,c,d: ((a/b)*(c/d),
    lambda a,b,c,d: ((a*b)+(c/d),
    lambda a,b,c,d: ((a*b)/(c+d),
    lambda a,b,c,d: ((a/b)*(c+d),
    lambda a,b,c,d: ((a+b)/(c*d),
    lambda a,b,c,d: ((a*b)-(c/d),
    lambda a,b,c,d: ((a*b)/(c-d),
    lambda a,b,c,d: ((a/b)-(c*d),
    lambda a,b,c,d: ((a/b)*(c-d),
    lambda a,b,c,d: ((a-b)/(c*d),
    lambda a,b,c,d: ((a+b)*(c+d),
    lambda a,b,c,d: ((a*b)-(c+d),
    lambda a,b,c,d: ((a*b)+(c-d),
    lambda a,b,c,d: ((a+b)-(c*d),
    lambda a,b,c,d: ((a+b)*(c-d),
    lambda a,b,c,d: ((a*b)-(c-d),
    lambda a,b,c,d: ((a-b)-(c*d),
    lambda a,b,c,d: ((a-b)*(c-d),
    lambda a,b,c,d: ((a/b)/(c/d),
    lambda a,b,c,d: ((a/b)+(c/d),
    lambda a,b,c,d: ((a/b)/(c+d),
    lambda a,b,c,d: ((a+b)/(c/d),
    lambda a,b,c,d: ((a/b)-(c/d),
    lambda a,b,c,d: ((a/b)/(c-d),
    lambda a,b,c,d: ((a-b)/(c/d),
    lambda a,b,c,d: ((a+b)/(c+d),
    lambda a,b,c,d: ((a/b)-(c+d),
    lambda a,b,c,d: ((a/b)+(c-d),
    lambda a,b,c,d: ((a+b)-(c/d),
    lambda a,b,c,d: ((a+b)/(c-d),
    lambda a,b,c,d: ((a-b)/(c+d),
    lambda a,b,c,d: ((a/b)-(c-d),
    lambda a,b,c,d: ((a-b)-(c/d),
    lambda a,b,c,d: ((a-b)/(c-d),
    lambda a,b,c,d: ((a+b)-(c+d),
    lambda a,b,c,d: ((a+b)+(c-d),
    lambda a,b,c,d: ((a+b)-(c-d),
    lambda a,b,c,d: ((a-b)-(c+d),
    lambda a,b,c,d: ((a-b)+(c-d),
    lambda a,b,c,d: ((a-b)-(c-d)]

formats = [
    "(({0}*{1})*{2})*{3}",
    "(({0}*{1})+{2})*{3}",
    "(({0}+{1})*{2})*{3}",
    "(({0}*{1})-{2})*{3}",
    "(({0}/{1})+{2})*{3}",
    "(({0}-{1})*{2})*{3}",
    "(({0}/{1})-{2})*{3}",
    "(({0}+{1})+{2})*{3}",
    "(({0}+{1})-{2})*{3}",
    "(({0}-{1})-{2})*{3}",
    "(({0}*{1})*{2})/{3}",
    "(({0}*{1})/{2})/{3}",
    "(({0}*{1})+{2})/{3}",
    "(({0}+{1})*{2})/{3}",
    "(({0}*{1})-{2})/{3}",
    "(({0}-{1})*{2})/{3}",
    "(({0}/{1})/{2})/{3}",
    "(({0}/{1})+{2})/{3}",
    "(({0}+{1})/{2})/{3}",
    "(({0}/{1})-{2})/{3}",
    "(({0}-{1})/{2})/{3}",
    "(({0}+{1})+{2})/{3}",
    "(({0}+{1})-{2})/{3}",
    "(({0}-{1})-{2})/{3}",
    "(({0}*{1})*{2})+{3}",
    "(({0}*{1})/{2})+{3}",
    "(({0}*{1})+{2})+{3}",
    "(({0}+{1})*{2})+{3}",
    "(({0}-{1})*{2})+{3}",
    "(({0}/{1})/{2})+{3}",
    "(({0}/{1})+{2})+{3}",
    "(({0}+{1})/{2})+{3}",
    "(({0}-{1})/{2})+{3}",
    "(({0}+{1})+{2})+{3}",
    "(({0}*{1})*{2})-{3}",
    "(({0}*{1})/{2})-{3}",
    "(({0}*{1})+{2})-{3}",
    "(({0}+{1})*{2})-{3}",
    "(({0}*{1})-{2})-{3}",
    "(({0}-{1})*{2})-{3}",
    "(({0}/{1})/{2})-{3}",
    "(({0}/{1})+{2})-{3}",
    "(({0}+{1})/{2})-{3}",
    "(({0}/{1})-{2})-{3}",
    "(({0}-{1})/{2})-{3}",
    "(({0}+{1})+{2})-{3}",
    "(({0}+{1})-{2})-{3}",
    "(({0}-{1})-{2})-{3}",
    "(({0}*{1})/({2}*{3}"),
    "(({0}*{1})*({2}/{3}"),
    "(({0}*{1})+({2}*{3}"),
    "(({0}*{1})-({2}*{3}"),
    "(({0}*{1})/({2}/{3}"),
    "(({0}/{1})/({2}*{3}"),
    "(({0}/{1})*({2}/{3}"),
    "(({0}*{1})+({2}/{3}"),
    "(({0}*{1})/({2}+{3}"),
    "(({0}/{1})*({2}+{3}"),
    "(({0}+{1})/({2}*{3}"),
    "(({0}*{1})-({2}/{3}"),
    "(({0}*{1})/({2}-{3}"),
    "(({0}/{1})-({2}*{3}"),
    "(({0}/{1})*({2}-{3}"),
    "(({0}-{1})/({2}*{3}"),
    "(({0}+{1})*({2}+{3}"),
    "(({0}*{1})-({2}+{3}"),
    "(({0}*{1})+({2}-{3}"),
    "(({0}+{1})-({2}*{3}"),
    "(({0}+{1})*({2}-{3}"),
    "(({0}*{1})-({2}-{3}"),
    "(({0}-{1})-({2}*{3}"),
    "(({0}-{1})*({2}-{3}"),
    "(({0}/{1})/({2}/{3}"),
    "(({0}/{1})+({2}/{3}"),
    "(({0}/{1})/({2}+{3}"),
    "(({0}+{1})/({2}/{3}"),
    "(({0}/{1})-({2}/{3}"),
    "(({0}/{1})/({2}-{3}"),
    "(({0}-{1})/({2}/{3}"),
    "(({0}+{1})/({2}+{3}"),
    "(({0}/{1})-({2}+{3}"),
    "(({0}/{1})+({2}-{3}"),
    "(({0}+{1})-({2}/{3}"),
    "(({0}+{1})/({2}-{3}"),
    "(({0}-{1})/({2}+{3}"),
    "(({0}/{1})-({2}-{3}"),
    "(({0}-{1})-({2}/{3}"),
    "(({0}-{1})/({2}-{3}"),
    "(({0}+{1})-({2}+{3}"),
    "(({0}+{1})+({2}-{3}"),
    "(({0}+{1})-({2}-{3}"),
    "(({0}-{1})-({2}+{3}"),
    "(({0}-{1})+({2}-{3}"),
    "(({0}-{1})-({2}-{3}")]    

rules = zip(expressions, formats)

solnlist = set()
for expr, fmt in rules: # for every unique way of combining four numbahs
    for n in permutations(numbahs):  # and every permutation of numbers
        try:
            if expr(*n) == ansah:
                solnlist.add(fmt.format(*n))
        except:
            pass

print ("There were {0} solutions:".format(len(solnlist)))
for s in solnlist:
    print (s)
